### ISSUE TITLE
Windows path resolution error during runtime

### ISSUE THREAD

**Issue by tonyketcham** [FlatbreadLabs/flatbread#78]
Running a Flatbread integration on Windows yields this error:
```bash
TypeError [ERR_INVALID_ARG_VALUE]: The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received 'file://D:a\flatbread\flatbreadpackagesconfig\tsup.config.ts'
    at new NodeError (node:internal/errors:372:5)
    at createRequire (node:internal/modules/cjs/loader:1220:13)
    at file:///D:/a/flatbread/flatbread/packages/config/dist/index.js:5:17
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async getConfig (file:///D:/a/flatbread/flatbread/packages/flatbread/dist/graphql/server.js:12:26)
    at async file:///D:/a/flatbread/flatbread/packages/flatbread/dist/graphql/server.js:23:14 {
  code: 'ERR_INVALID_ARG_VALUE'
}
```

**Comment by Sheharyar566** [comment]
Testing on my side
